config/routes.rb
Rails.application.routes.draw do
  resources :stats do
    collection do
      post :start_handler
      get :print_stats
      post :setpoint
    end
  end
  root 'stats#index'

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :stat
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :stat
end

app/models/spent_time.rb
class SpentTime < ActiveRecord::Base
  belongs_to :stat
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  has_many :spent_times, :dependent => :destroy 
  has_many :directions, :dependent => :destroy
  has_many :positions, :dependent => :destroy
end

app/models/velocity.rb
class Velocity < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]

  # GET /stats
  # GET /stats.json
  def index
    @stats = Stat.all
  end


 # def setpoint
  #  setpoint = params[:setpoint]

   # handler = port_handler
    #handler.send_setpoint(setpoint)
    #redirect_to root_path, notice: 'Setpoint successfully sent!'

 # end
  # GET /stats/1
  # GET /stats/1.json
  def show
   # @times = @stat.spent_times.pluck(:data)
    @position = @stat.positions.pluck(:data)
    @chart = LazyHighCharts::HighChart.new('basic_line') do |f|
   f.chart( {
            type: 'spline'
        })
   f.title( {
            text: 'Stats'
        })
          f.xAxis({
            title:{
             text: 'Time'
            }
        })
        f.yAxis( {
            title: {
                text: 'Position'
            }

        })

        f.plotOptions( {
            spline: {
                lineWidth: 1,
                states: {
                    hover: {
                        lineWidth: 2
                    }
                },
                marker: {
                    enabled: false
                }


            }
        })
        f.series({
            name: 'Position',
            data: @position

        } )
  end

  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render :show, status: :created, location: @stat }
      else
        format.html { render :new }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  def start_handler

    stat = Stat.new
    handler = port_handler
    handler.send_char
    handler.read_port

    @position = handler.position.map(&:to_i)
    @time = handler.time.map(&:to_i)
    @direction = handler.direction.map(&:to_i)

    @direction.each do |x|
      Direction.create(stat: stat, data: x)
    end

    @time.each do |x|
      SpentTime.create(stat: stat, data: x)
    end

    @position.each do |x|
      Position.create(stat: stat, data: x)
    end

    @chart = LazyHighCharts::HighChart.new('basic_line') do |f|
     f.chart( {
            type: 'spline'
        })
   f.title( {
            text: 'Stats'
        })
          f.xAxis({
            title:{
             text: 'Time'
            }
        })
        f.yAxis( {
            title: {
                text: 'Position'
            }

        })

        f.plotOptions( {
            spline: {
                lineWidth: 1,
                states: {
                    hover: {
                        lineWidth: 2
                    }
                },
                marker: {
                    enabled: false
                }


            }
        })
        f.series({
            name: 'Position',
            data: @position

        } )
    end
    render :print_stats
  end

  def print_stats
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @stat }
      else
        format.html { render :edit }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url, notice: 'Stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stat
    @stat = Stat.find(params[:id])
  end

  def port_handler
    @port_handler ||= PortHandler.new
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stat_params
    params.require(:stat).permit(:position, :time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="loader" class="spinner">
   <div class="rect1"></div>
   <div class="rect2"></div>
   <div class="rect3"></div>
   <div class="rect4"></div>
  <div class="rect5"></div>
</div>
  <div id="loading" class="loadname"> <span>Loading in progress, please wait </span> </div>
  <div id="content">
    <%= flash[:notice] %>
  <%= yield %>
  </div>
</body>
</html>

app/views/stats/_form.html.erb
<%= form_for(@stat) do |f| %>
  <% if @stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
      <% @stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

app/views/stats/index.html.erb
<h1>Press button to start</h1>
<%= button_to 'Start', start_handler_stats_path, id: "start" %>
<br />

<table>
  <tbody>
    <h1>Last charts</h1>
    <% @stats.each do |stat| %>
    <tr> 
      <td><%= stat.created_at %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stats/new.html.erb
<h1>Start</h1> 

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

app/views/stats/print_stats.html.erb
<h1>Stats</h1>

<%= high_chart("some_id", @chart) %>


<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<h1>Stats</h1>
<div><%= high_chart("some_id", @chart) %></div>
<h1></h1>
<%= link_to 'Back', stats_path %>